sonar.projectKey=octaviodemos_prova02-unit-test-OctavioDemos
sonar.organization=octaviodemos
sonar.projectName=prova02-unit-test-OctavioDemos
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8